name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.300
      - name: Build Core
        run: dotnet build --configuration Release
        working-directory: ./Oatmilk
      - name: Build Xunit
        run: dotnet build --configuration Release
        working-directory: ./Oatmilk.Xunit
