name: release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.300
      - name: Pack Core
        run: dotnet pack --configuration Release ./src/Oatmilk /p:Version=${{ github.event.release.tag_name }}
      - name: Pack Xunit
        run: dotnet pack --configuration Release ./src/Oatmilk.Xunit /p:Version=${{ github.event.release.tag_name }}
      - name: Push All
        run: find . \( -name "*.nupkg" \) | xargs -n1 dotnet nuget push -s nuget.org -k $PUSH_KEY --skip-duplicate
        env:
          PUSH_KEY: ${{ secrets. NUGET_PUSH_KEY }}
